[package]
name = "near-cli-extension-example"
version = "0.1.0"
authors = ["Serhii Volovyk <sergeyvolovyk@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
anyhow = "1.0"
